// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proj_APBD.Server.Contexts;

#nullable disable

namespace Proj_APBD.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230619122922_StocksInit")]
    partial class StocksInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proj_APBD.Server.Models.Stock", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Ticker");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("Proj_APBD.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("489e4c7c-004b-4b6c-9488-6b37f5e18c1f"),
                            Password = "AQAAAAIAAYagAAAAEEJO4LuCMB1w3MPT/+ZpuSIsBse2HRuBfi01fS3Wnk9dlahVlaPT52diyojD3QsN7g==",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("StockUser", b =>
                {
                    b.Property<string>("StocksTicker")
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StocksTicker", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("StockUser");
                });

            modelBuilder.Entity("StockUser", b =>
                {
                    b.HasOne("Proj_APBD.Server.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StocksTicker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proj_APBD.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
